version: "3"
services:
  express-web-app-dev:
    image: node:10-alpine
    container_name: express-web-app-dev
    tty: true
    environment: 
      - APP_PORT=3000
    ports:
      - 3000:3000
    working_dir: /home/app
    volumes:
      - ./app/:/home/app
